#!/usr/bin/env bash
echo "Create bucket "


if [ -z "$1" ]; then 
   echo "There needs to be a bucket name"
   exit 1
fi

BUCKET_NAME=$1
REGION=us-east-1


aws s3api create-bucket \
 --bucket "$BUCKET_NAME" \
 --region "$REGION"
