#!/usr/bin/env bash
echo "Delete bucket "


if [ -z "$1" ]; then 
   echo "There needs to be a bucket name"
   exit 1
fi

BUCKET_NAME=$1
REGION=us-east-1


aws s3api list-objects-v2 \
 --bucket "$BUCKET_NAME" 
